language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker

before_install:
  - docker build -t mrwin95/frontend:1 -f Dockerfile.dev .

script: 'true'

deploy:
  provider: elasticbeantalk
  region: "ap-southeast-1"
  app: "docker-angular"
  env: "DockerAngular-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-009876694182"
  bucket_path: "docker-angular"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
